### PR TITLE
planning-3

### PR DESCRIPTION
**Pull request by KarlieKKY**

### CODE REVIEW

**Review by HannahBurks — CHANGES_REQUESTED** [review]
A nice start Karlie, but still some further planning to think about. 

- How are we going to get to ‘/categories’ and ‘/users’ from ‘/‘ -do we click something?
- Are we going to have all the review's contents, all comments and votes rendered onto the same page (/reviews) rather than having an individual review page that we can see the individual review in depth, read all comments and vote + add a comment? - your choice here, but think about how busy this page may be if you decide on this.
- I would also like to see you think about what states we need and where in the component tree they need to be and passed down to
- We also want to show how we can post a comment and vote on a review
- I would also like to see a plan of the end points from the api you are going to use and where these requests will need to be made. 

Once you have implemented these changes, please send another pull request. 😄

**Review by dappernerddesigns — CHANGES_REQUESTED** [review]
Hi Karlie, your plan here is getting better but not quite there.

Your component tree is very confusing about how you are planning to structure your application. Which component is a child of another component? Where are you using state and what are you using state for?

Your diagram almost implies passing a single state on props to every component and then back up the tree. It is almost impossible to pass state from a sibling component to another. Please have another go at designing this tree, what component will be accessed from App. From those components, which ones will render child components? Which components will need to useSate, and which components will be sent information on props?

The component tree is designed to help you plan how you're going to build this application and give you something to refer back to during the week.

For users, whenever you go to a website, are you presented with a list of possible users? Or are you asked to sign in? 

As we don't have any authentication on our BE server, it is fine to use a hard coded user perhaps using a useContext or even just in your comments components so that we are able to act as this user.

Please consider these points, amend your plan and resubmit this pull request.

**Comment by dappernerddesigns** [comment]
You component tree is showing 4 different sets of state held in App. Prop drilling to get state to the lower components is not what we're looking for. We need state to be as low as possible, but as high as necessary for any child component. Why would comments be a child of reviews by category? Comments are per review, we wouldn't view a list of comments for a review or article we weren't reading. 

I would be expecting an authentication or useContext in App, I agree. But the state for reviews wouldn't be needed until the reviews components.

I'm happy with your general layout, but before you start coding I really need you to think about where it is appropriate to store state. I'm going to approve this, but bear in mind if state is in an inappropriate place when submitting code we will ask you to reconsider it.

**Review by dappernerddesigns — APPROVED** [review]
Really think about where state should be when you move on.

**Pull request merged**
